### ISSUE TITLE
METADATA needs sha1 bump

### ISSUE THREAD

**Issue by milktrader** [JuliaLang/Iterators.jl#14]
Installing the package via the package manager doesn't export the `imap` method, but the latest commit has it defined.

**Comment by schmrlng** [comment]
Bumping this old issue as the title seems apt - this time it's ```repeatedly``` that's exported in the latest commit, but not in the current version ([0.1.7](https://github.com/JuliaLang/METADATA.jl/tree/metadata-v2/Iterators/versions)) on METADATA.jl.
