### ISSUE TITLE
take(Any,Int64) shadows Base method in 0.4

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/Iterators.jl#41]
```jl
> using Iterators
Warning: Method definition take(Any,Int64) in module Base at iterator.jl:129 overwritten in module Iterators at /Users/jiahao/.julia/v0.4/Iterators/src/Iterators.jl:50.
```

**Comment by garborg** [comment]
See #39. I was thinking about moving the meat of the PR over to Compat.jl and having Iterators just use that instead, but I was waiting on feedback.

**Comment by lindahua** [comment]
I also ran into this today.

**Comment by garborg** [comment]
Sorry, forgot about this. Will clean up some time today.

**Comment by zenna** [comment]
Did this get fixed?

**Comment by garborg** [comment]
#39 fixes it, but not sure if it will be accepted.

**Comment by yuyichao** [comment]
#39 is already merged.
