### ISSUE TITLE
METADATA version bump

### ISSUE THREAD

**Issue by schmrlng** [JuliaLang/Iterators.jl#48]
The current version of this package ([0.1.7](https://github.com/JuliaLang/METADATA.jl/tree/metadata-v2/Iterators/versions)) registered on METADATA.jl doesn't export any of the iterators added in the last few months (```repeatedly``` among others). I don't have the access rights to publish a new tag myself; can somebody help me out?

**Comment by kmsquire** [comment]
Done!
