### ISSUE TITLE
make @itr optimizations default in core

### ISSUE THREAD

**Issue by holocronweaver** [JuliaLang/Iterators.jl#49]
By default, Python 3 uses iterators for loop operations like `zip` and `enumerate`. Thus there is no need for a macro like `@itr`. I am new to Julia and have difficulty understanding why the default behavior would not use iterators. Are there any plans for Julia core to make a similar transition to iterator-only loops like Python did?

Thanks!

**Comment by StefanKarpinski** [comment]
This kind of question is more appropriate as a question on julia-users. Would you mind posting it there?

**Comment by holocronweaver** [comment]
Thanks, posted on julia-users - currently awaiting moderation.
