### ISSUE TITLE
no method matching length(::Iterators.Chain)

### ISSUE THREAD

**Issue by lmshk** [JuliaLang/Iterators.jl#56]
On edge julia, Iterators.jl tests fail on

    Expression: collect(chain(1:2:5,0.2:0.1:1.6)) == [1:2:5;0.2:0.1:1.6]

with

    MethodError: no method matching length(::Iterators.Chain)

Possibly this is due to [Julia #15146](https://github.com/JuliaLang/julia/pull/15146). See also #42.

**Comment by oxinabox** [comment]
See also https://github.com/JuliaLang/julia/issues/15977

Basically it is required to go through and implement  `Base.iteratorsize` on everything.
Which would not be unfun to do.
