### ISSUE TITLE
Shuffle order?

### ISSUE THREAD

**Issue by ahwillia** [JuliaLang/Iterators.jl#61]
I'm interested in a for loop like:

```julia
# iterate i = 1:10 in random order
for i in shuffle(collect(1:10))
end
```

Is there an iterator for that?

**Comment by stevengj** [comment]
`for i in randperm(10)`

**Comment by ahwillia** [comment]
Of course, thank you. But if this happens in an inner for loop it will allocate a bunch of arrays?

**Comment by StefanKarpinski** [comment]
If you pre-allocate an array of indices, you can call `shuffle!` on it in the inner loop and no allocation will occur. If you want to get more efficient than that, you'll need to avoid materializing the array of indices.

**Comment by mschauer** [comment]
In any case for this you need to collect the iterator into an array-like structure in one way or the other. There can't really be a clean ``start``- ``next``- ``end``-solution to this.

**Comment by ahwillia** [comment]
Thanks guys! Closing this, as Stefan's suggestion seems to cover most reasonable use cases I can think of.
